version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.25.1
    ports:
      - "8080:8080"      # REST API
      - "50051:50051"    # gRPC API
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'

      # gRPC
      GRPC_PORT: '50051'

      # Включаем модуль ollama
      ENABLE_MODULES: 'text2vec-ollama'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'

      # Указываем эндпоинт ollama
      OLLAMA_API_ENDPOINT: 'http://host.docker.internal:11434'  # или замени, если на Linux

    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure

volumes:
  weaviate_data:
